### ISSUE TITLE
DFT transform along dims...

### ISSUE THREAD

**Issue by 1oly** [kul-forbes/AbstractOperators.jl#12]
Hi again,

This is related to #11 but may be more a feature request if I'm not mistaken.

In [FFTW.jl/fft.jl](https://github.com/JuliaMath/FFTW.jl/blob/d2b22f4c6b13d7b26974419796725eac7f48082e/src/fft.jl) it is possible to specify the dimensions along which to transform with an optional arg `dims`. This option doesn't seem to be supported in the `DFT` operator (or `IDFT`). Is that correct?

MWE:

```
using FFTW, AbstractOperators
A = rand(3,3)
fftA = fft(A) # equivalent to fft(A,(1,2))
DF = DFT(ones(3,3))
DF*A == fftA # true
# but if I what to transform along only one dim
fft(A,1) == DF*A # false
```

Is there an easy way around this or would it make sense to add as a feature?

Thanks,
Oliver.

EDIT:

Can see you already have it in `IRDFT` [IRDFT](https://github.com/kul-forbes/AbstractOperators.jl/blob/1e5a7a93bac28528fe442c04b399f82e59f30a39/src/linearoperators/IRDFT.jl#L4)...

**Comment by nantonel** [comment]
Yes I don't know why haven't added it... probably laziness 😄 
It should be quite easy to add that! If you want you can give it a shot and try to submit a PR. 😉  
Otherwise I'll try to add this feature as soon as I have some time!

**Comment by 1oly** [comment]
I'd be happy to give it a go with a PR. Just to make sure how that would pan out, mimicking from RDFT: https://github.com/kul-forbes/AbstractOperators.jl/blob/e16bbe48e82c334e9435b6692e621f72a73373cd/src/linearoperators/RDFT.jl#L41

adding a `dims` to DFT/IDFT (should actually not be constrained to ::Int as in RDFT/IRDFT, right? I often transform 3d arrays along `dims=(1,2)` with fft).

**Comment by nantonel** [comment]
Hi! Sorry for the late reply! Yes you're right, I guess you could use a `Union` or drop the type there.
In general the idea here is to keep the calls as close as possible to e.g. `rfft`.

**Comment by nantonel** [comment]
Thanks for the PR #13 @1oly! 😄
