### ISSUE TITLE
avoid parsing strings ending with commas

### ISSUE THREAD

**Issue by JeffBezanson** [kul-forbes/AbstractOperators.jl#6]
As of julia 1.1 `x,` is considered incomplete input, which is causing generated functions in this package to fail with parse errors. Trailing commas should be removed (or better yet use expression quoting instead of calling `parse`).

**Comment by nantonel** [comment]
Thanks for letting us know. We'll try to fix this the soonest!

**Comment by nantonel** [comment]
The problem has been fixed in [this commit](https://github.com/kul-forbes/AbstractOperators.jl/commit/087f8cc0d68f7128f2e7ce0b94402b169bb52ddb): test on master are now passing on Julia nightly.
